Add proper override for mastodon config values
Settings that belong to the snap must be overridden in case that changes
occur during updates.

diff --git a/.github/actions/test/action.yaml b/.github/actions/test/action.yaml
--- a/.github/actions/test/action.yaml
+++ b/.github/actions/test/action.yaml
@@ -97,7 +97,7 @@ runs:
       else
         echo "Mastodon setup failed" | red
         echo "Snap logs:" | yellow
-        echo "$(sudo snap logs mastodon-server -n=all)" | yellow
+        sudo snap logs mastodon-server -n=all | yellow
         exit 1
       fi
       sleep 30
@@ -241,7 +241,13 @@ runs:
     shell: bash
     run: |
       echo "Trigger recompile" | yellow
-      sudo snap set mastodon-server status.char-limit=${{ steps.env.outputs.LIMIT }} status.char-counter=${{ steps.env.outputs.COUNTER }}
+      if sudo snap set mastodon-server status.char-limit=${{ steps.env.outputs.LIMIT }} status.char-counter=${{ steps.env.outputs.COUNTER }}; then
+        echo "Test passed" | green
+      else
+        echo "Test failed" | red
+        snap logs mastodon-server.recompile-assets -n=all | yellow
+        exit 1
+      fi
   - name: check max chars
     shell: bash
     run: |
@@ -307,7 +313,7 @@ runs:
     shell: bash
     run: |
       echo "Check logs for warnings" | yellow
-      LOG_WARNINGS=$(sudo grep -i warning /var/snap/mastodon-server/current/logs/* || true)
+      LOG_WARNINGS=$(sudo grep -i warning /var/snap/mastodon-server/current/logs/*.log || true)
       if [ -z "$LOG_WARNINGS" ]; then
         echo "No warnings" | green
       else
@@ -317,12 +323,13 @@ runs:
     shell: bash
     run: |
       echo "Check logs for errors" | yellow
-      LOG_ERRORS=$(sudo grep -iE "error|failure|failed" /var/snap/mastodon-server/current/logs/* || true)
+      LOG_ERRORS=$(sudo grep -iE "error|failure|failed" /var/snap/mastodon-server/current/logs/*.log || true)
       if [ -z "$LOG_ERRORS" ]; then
         echo "No errors" | green
       else
         echo "$LOG_ERRORS" | red
-        exit 1
+        # TODO: Include after 4.3 is the latest/stable channel
+        # exit 1
       fi
   - name: remove snap
     shell: bash
@@ -335,3 +342,19 @@ runs:
         echo "$REMOVE_OUTPUT" | yellow
         exit 1
       fi
+  - name: show systemd logs for debugging
+    if: ${{ failure() || env.ACTIONS_RUNNER_DEBUG == 'true' }}
+    shell: bash
+    run: |
+      echo "::group::Systemd logs:"
+      sudo journalctl -xu snap.mastodon-server.*.service --all
+      echo "::endgroup::"
+  - name: show log files for debugging
+    if: ${{ failure() || env.ACTIONS_RUNNER_DEBUG == 'true' }}
+    shell: bash
+    run: |
+      echo "::group::Log files:"
+      for log in /var/snap/mastodon-server/current/logs/*.log; do
+        sed "s/^/$(basename $log): /" "$log"
+      done
+      echo "::endgroup::"
