Improve test workflow output

diff --git a/.github/actions/test/action.yaml b/.github/actions/test/action.yaml
--- a/.github/actions/test/action.yaml
+++ b/.github/actions/test/action.yaml
@@ -33,7 +33,13 @@ runs:
       sudo snap install --dangerous ${{ inputs.snap }}
       sudo snap set mastodon-server domain="${{ steps.env.outputs.domain }}"
       sudo snap set mastodon-server email="admin@${{ steps.env.outputs.domain }}"
-      sudo mastodon-server.setup
+      if SETUP_OUTPUT=$(sudo mastodon-server.setup); then
+        echo -e "\033[1;32mMastodon setup completed successfully\033[0m"
+      else
+        echo -e "\033[1;31mMastodon setup failed\033[0m"
+        echo -e "\033[1;33m$SETUP_OUTPUT\033[0m"
+        exit 1
+      fi
   - name: check services
     shell: bash
     run: |
@@ -99,9 +105,9 @@ runs:
       sleep 30
       HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --resolve "${{ steps.env.outputs.domain }}:${{ steps.env.outputs.HTTP_PORT }}:127.0.0.1" "http://${{ steps.env.outputs.domain }}:${{ steps.env.outputs.HTTP_PORT }}")
       if [ "$HTTP_STATUS" -eq 301 ]; then
-        echo -e "\033[1;32mHTTP to HTTPS forwarding works\033[0m"
+        echo -e "\033[1;32mHTTP to HTTPS forwarding is active\033[0m"
       else
-        echo -e "\033[1;31mHTTP to HTTPS forwarding does not work\033[0m"
+        echo -e "\033[1;31mHTTP to HTTPS forwarding is inactive\033[0m"
         echo -e "\033[1;33m$HTTP_STATUS\033[0m"
         exit 1
       fi
@@ -122,7 +128,7 @@ runs:
     run: |
       echo -e "\033[1;33mTest export\033[0m"
       if EXPORT_OUTPUT=$(sudo mastodon-server.export); then
-        echo -e "\033[1;32mExport command works\033[0m"
+        echo -e "\033[1;32mExport command completed successfully\033[0m"
       else
         echo -e "\033[1;31mThere occured an error during export\033[0m"
         echo -e "\033[1;33m$EXPORT_OUTPUT\033[0m"
@@ -136,7 +142,7 @@ runs:
     run: |
       echo -e "\033[1;33mTest restore\033[0m"
       if RESTORE_OUTPUT=$(sudo mastodon-server.restore ${{ steps.export.outputs.backup_dir }}); then
-        echo -e "\033[1;32mRestore command works\033[0m"
+        echo -e "\033[1;32mRestore command completed successfully\033[0m"
       else
         echo -e "\033[1;31mThere occured an error during restore\033[0m"
         echo -e "\033[1;33m$RESTORE_OUTPUT\033[0m"
@@ -187,7 +193,7 @@ runs:
           echo -e "\033[1;33m$CONSOLE_OUTPUT\033[0m"
           exit 1
         else
-          echo -e "\033[1;32mmastodon-server.console works\033[0m"
+          echo -e "\033[1;32mmastodon-server.console works as expected\033[0m"
         fi
       fi
   - name: test postgres dump
@@ -200,6 +206,6 @@ runs:
           echo -e "\033[1;33m$POSTGRES_DUMP\033[0m"
           exit 1
         else
-          echo -e "\033[1;32mmastodon-server.postgres-dump works\033[0m"
+          echo -e "\033[1;32mmastodon-server.postgres-dump completed successfully\033[0m"
         fi
       fi
