Add generate-wrapstodon command

diff --git a/.github/actions/test/action.yaml b/.github/actions/test/action.yaml
--- a/.github/actions/test/action.yaml
+++ b/.github/actions/test/action.yaml
@@ -321,6 +321,17 @@ runs:
           exit 1
         fi
       fi
+  - name: test wrapstodon feature
+    shell: bash
+    run: |
+      echo "Test wrapstodon feature" | yellow
+      if WRAPSTODON_OUTPUT="$(sudo mastodon-server.generate-wrapstodon)"; then
+        echo "Test passed" | green
+      else
+        echo "Test failed" | red
+        echo "$WRAPSTODON_OUTPUT" | yellow
+        exit 1
+      fi
   - name: test postgres dump
     shell: bash
     run: |
