Fix and improve review workflow

diff --git a/.github/workflows/review.yaml b/.github/workflows/review.yaml
--- a/.github/workflows/review.yaml
+++ b/.github/workflows/review.yaml
@@ -18,28 +18,37 @@ jobs:
           - builder: ubuntu-latest
             arch: amd64
     steps:
-    - name: install dependencies
+    - name: install review-tools
       shell: bash
-      run: |
-        sudo apt install jq -y
-        sudo snap install review-tools
+      run: sudo snap install review-tools
     - name: download snap
       uses: robinraju/release-downloader@v1
       with:
         latest: true
         tag: ${{ inputs.ref }}
         fileName: "mastodon-server_*_amd64.snap"
+      id: download
     - name: check notices
       shell: bash
       env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         GH_REPO: ${{ github.repository }}
       run: |
-        review_results=$(review-tools.check-notices ./mastodon-server_*_amd64.snap)
-        version=$(echo "$json_output" | jq -r '.["mastodon-server"] | keys[0]')
-        packages=$(echo "$json_output" | jq -r ".\"mastodon-server\".\"$version\"")
+        snap_file=$(basename "${{ fromJson(steps.download.outputs.downloaded_files)[0] }}")
+        sudo mv $snap_file /root/
+        sudo chown root "/root/$snap_file"
+        review_results=$(sudo review-tools.check-notices /root/$snap_file)
+        version=$(echo "$review_results" | jq -r '.["mastodon-server"] | keys[0]')
+        if [ -z "$version" ]; then
+          echo -e "\033[31mVersion not found\033[0m"
+          echo "$review_results"
+          exit 1
+        fi
+        packages=$(echo "$review_results" | jq -r ".\"mastodon-server\".\"$version\"")
+        title="Vulnerabilities found for release $version"
         body=""
         if [ "$packages" != "{}" ]; then
+          echo -e "\033[31m$title\033[0m"
           for package in $(echo "$packages" | jq -r 'keys[]'); do
             body="$body**$package**:\n"
             usns=$(echo "$packages" | jq -r ".\"$package\"[]")
@@ -47,8 +56,13 @@ jobs:
               body="$body- http://ubuntu.com/security/notices/$usn\n"
             done
           done
-          title="Vulnerabilities found for release $version"
-          if [ -z "$(gh search issues --match title "$title")" ]; then
+          existing_issue=$(gh search issues --match title "$title" --json number,title --jq ".[] | select(.title == \"$title\")")
+          if [ -z "$existing_issue" ]; then
+            echo -e "\033[33mCreating new GitHub issue\033[0m"
             gh issue create --title "$title" --body "$body" --label security
+          else
+            issue_number=$(echo "$existing_issue" | jq -r ".number")
+            echo -e "\033[33mAdd comment to existing GitHub issue $issue_number\033[0m"
+            gh issue comment "$issue_number" --body "$body"
           fi
         fi
